# Generated by Django 6.0.2 on 2026-02-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
    ]
