# Generated by Django 6.0.2 on 2026-03-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_delete_customerprofile'),
        ('products', '0002_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='mainApp.producerprofile'),
        ),
    ]
