# Generated by Django 6.0.2 on 2026-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('celery', 'Celery'), ('cereals_gluten', 'Cereals containing gluten (wheat, rye, barley, oats)'), ('crustaceans', 'Crustaceans (prawns, crabs, lobster)'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('lupin', 'Lupin'), ('milk', 'Milk'), ('molluscs', 'Molluscs (mussels, oysters, snails)'), ('mustard', 'Mustard'), ('nuts', 'Nuts (almonds, hazelnuts, walnuts, etc.)'), ('peanuts', 'Peanuts'), ('sesame', 'Sesame seeds'), ('soya', 'Soya'), ('sulphites', 'Sulphur dioxide / sulphites')], max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the allergen', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'allergen',
                'verbose_name_plural': 'allergens',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='allergen_notes',
            field=models.CharField(blank=True, help_text='Brief allergen warning for quick display', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='allergen_statement',
            field=models.TextField(blank=True, help_text="Additional allergen information or preparation notes (e.g., 'May contain traces of nuts due to shared equipment')"),
        ),
        migrations.AddField(
            model_name='product',
            name='has_allergens',
            field=models.BooleanField(default=False, help_text='Does this product contain any allergens?'),
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, help_text='Select all allergens present in this product', related_name='products', to='products.allergen'),
        ),
    ]
