# Generated by Django 6.0.2 on 2026-03-13 11:07

import products.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_allergen_product_allergen_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to=products.utility.product_image_path),
        ),
    ]
