# Generated by Django 6.0.2 on 2026-04-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Timestamp when product was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False if product has been soft deleted (hidden from store but kept for historical orders)'),
        ),
    ]
