# Generated by Django 6.0.2 on 2026-04-07 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_producerprofile_user'),
        ('products', '0007_product_deleted_at_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='mainApp.producerprofile'),
        ),
    ]
