# Generated by Django 6.0.2 on 2026-03-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
