# Generated by Django 6.0.2 on 2026-03-06 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_customerprofile_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producerprofile',
            old_name='company_name',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='shipping_address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='UK', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longtitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('shipping', 'Shipping'), ('billing', 'Billing'), ('farm', 'Farm'), ('business', 'Business')], default='home', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'address_type', 'is_default'), name='unique_default_address')],
            },
        ),
    ]
