# Generated by Django 6.0.2 on 2026-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_rename_company_name_producerprofile_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
