# Generated by Django 6.0.2 on 2026-03-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_producerprofile_latitude_producerprofile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='shipping_address',
        ),
    ]
