# Generated by Django 6.0.2 on 2026-03-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_customerprofile_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
