# Generated by Django 6.0.2 on 2026-03-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_rename_longtitude_address_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularuser',
            name='address',
        ),
    ]
