# Generated by Django 6.0.2 on 2026-03-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_regularuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, help_text="e.g 'Mum's house', 'Business'", max_length=50),
        ),
    ]
