# Generated by Django 6.0.2 on 2026-03-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_address_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='longitude',
        ),
    ]
