# Generated by Django 6.0.2 on 2026-03-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_remove_producerprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='lead_time_hours',
            field=models.PositiveIntegerField(default=48, help_text='Minimum hours notice required before delivery'),
        ),
    ]
