# Generated by Django 6.0.2 on 2026-03-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_producerprofile_lead_time_hours'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_default_address',
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_address_per_user'),
        ),
    ]
