# Generated by Django 6.0.2 on 2026-04-07 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_regularuser_deleted_at_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
