# Generated by Django 6.0.2 on 2026-03-31 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_remove_producerprofile_latitude_and_more'),
        ('orders', '0002_alter_order_customer_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='mainApp.address'),
        ),
    ]
