# Generated by Django 6.0.2 on 2026-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_order_remove_orderitem_producer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducer',
            name='producer_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
