# Generated by Django 6.0.2 on 2026-03-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproducer_producer_payout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducer',
            old_name='status',
            new_name='order_status',
        ),
    ]
