# Generated by Django 6.0.2 on 2026-03-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_status_orderproducer_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducer',
            name='delivered_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
