# Generated by Django 6.0.2 on 2026-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderproducer_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='epires_at',
            field=models.DateTimeField(blank=True, help_text='when this pending order expires', null=True),
        ),
    ]
