# Generated by Django 6.0.2 on 2026-03-31 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderpayment_epires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpayment',
            old_name='epires_at',
            new_name='expires_at',
        ),
    ]
