# Generated by Django 6.0.2 on 2026-03-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_epires_at_orderpayment_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducer',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup/Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
