# Generated by Django 6.0.2 on 2026-04-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderpayment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='customer',
        ),
    ]
