# Generated by Django 6.0.2 on 2026-04-07 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_producerprofile_user'),
        ('orders', '0012_remove_orderpayment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='shipping_address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='mainApp.address'),
        ),
    ]
