# Generated by Django 6.0.2 on 2026-04-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderpayment_shipping_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducer',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproducer',
            name='food_mile_distance',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderproducer',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproducer',
            name='settlement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
