# Generated by Django 6.0.2 on 2026-04-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderproducer_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducer',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
