services:

  webapp:
    build: .
    container_name: brfn-app
    command: >
      sh -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py seed_producers &&
            python manage.py seed_customers &&
            python manage.py seed_allergens &&
            python manage.py seed_products &&
            python manage.py seed_admins &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
    - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=brfn_db
      - DB_USER=demo_user
      - DB_PASSWORD=demo_password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=secret
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: desd-brfn_db
    environment:
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=demo_password
      - POSTGRES_DB=brfn_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:8.4.1-alpine
    container_name: desd-brfn_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    command: celery -A BRFN worker -l info
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A BRFN beat -l info
    depends_on:
      - redis
      - db

volumes:
  db:
    external: false
    name: desd-brfn_db
