# Generated by Django 6.0.2 on 2026-04-09 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0016_alter_producerprofile_user'),
        ('orders', '0015_orderproducer_settled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_orders', models.PositiveBigIntegerField(default=0)),
                ('total_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('settlement_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_reference', models.CharField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymenet_settlements', to='mainApp.producerprofile')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('producer', 'week_start', 'week_end')},
            },
        ),
        migrations.CreateModel(
            name='SettlementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_created_at', models.DateTimeField()),
                ('order_completed_at', models.DateTimeField()),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_postcode', models.CharField(blank=True, max_length=20)),
                ('order_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_records', to='orders.orderproducer')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.paymentsettlement')),
            ],
            options={
                'unique_together': {('settlement', 'order_producer')},
            },
        ),
    ]
