# Generated by Django 6.0.2 on 2026-04-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettlement',
            name='tax_year',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
