# Generated by Django 6.0.2 on 2026-04-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentsettlement_tax_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettlement',
            name='tax_year',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=30, null=True),
        ),
    ]
