# Generated by Django 6.0.2 on 2026-04-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentsettlement_tax_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettlement',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
