# Generated by Django 6.0.2 on 2026-03-02 15:54

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0002_delete_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerUser',
            fields=[
                ('regularuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_name', models.CharField(max_length=50, verbose_name='Producer Contact')),
                ('producer_name', models.CharField(max_length=50, verbose_name='Producer')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('mainApp.regularuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
