# Generated by Django 6.0.2 on 2026-03-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProducerUser',
        ),
    ]
