# Generated by Django 6.0.2 on 2026-04-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_add_recipes_farmstories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmstory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Farm stories'},
        ),
    ]
